version: '3'
services:
  test-webserver:
    image: nginx:alpine
    container_name: test-webserver
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
    networks:
      - test-network

  test-php:
    container_name: test-php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - test-mysql
      - test-redis
    restart: unless-stopped
    ports:
      - 9000
    networks:
      - test-network

  test-mysql:
    container_name: test-mysql
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 33066:3306
    networks:
      - test-network

  test-redis:
    container_name: test-redis
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
    ports:
      - 63792:6379
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=511
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
